<?php
/**
 * @file for hook_permission(), ejabberd_auth_menu, JabberAuth, ejabberd_auth_admin_settings
 *
 * Implements hook_permission(), ejabberd_auth_menu, ejabberd_auth_admin_settings
 * System variables: ejabberd_php_cli, ejabberd_auth_path, ejabberd_auth_salt, ejabberd_auth_timeout
 *   ejabberd_auth_type
 * Uses JabberAuth class to create auth script to authenticate with Jabber server.
 * system variable
 * ejabberd_log_to_status 
 * 
 */

//[FIXME] creation du script d'auth sans forcement passer par la page d'admin

/**
 * Implemenation of hook_permission().
 * [TODO] Maybe hard to implement
 */
function ejabberd_auth_permission() {
  return array(
    'ejabberd_auth' => array(
      'title' => t('ejabberd_auth'),
      'description' => t('Administer ejabber settings ejabberd_auth'),
    ),
  );
}

/**
 * Menu item for ejabberd_auth for site administrators
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function ejabberd_auth_menu() {
  $items['admin/config/ejabberd_auth'] = array(
    'description' => 'Ejabberd auth with Drupal users',
    'title' => 'Ejabberd authentification',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ejabberd_auth_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Admin Settings for ejabberd, auth script, auth salt, timeout, auth_type,
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function ejabberd_auth_admin_settings($form, &$form_state) {
  $form['ejabberd_php_cli'] = array(
    '#type' => 'textfield',
    '#title' => 'PHP path',
    '#default_value' => variable_get('ejabberd_php_cli', '/usr/bin/php'),
    '#description' => t("Where is the php cli? (ejabberd_php_cli)"),
  );

  $form['ejabberd_auth_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Script path',
    '#default_value' => variable_get('ejabberd_auth_path', '/tmp/ejabberd_auth.phps'),
    '#description' => t("Where the auth script is generated - needs to be server writable (ejabberd_auth_path)"),
  );

  $form['ejabberd_auth_salt'] = array(
    '#type' => 'textfield',
    '#title' => 'Salt',
    '#default_value' => variable_get('ejabberd_auth_salt', 'Casimir'),
    '#description' => t("The secret word, don't keep the default one (ejabberd_auth_salt)"),
  );

  $form['ejabberd_auth_timeout'] = array(
    '#type' => 'textfield',
    '#title' => 'Timeout (ejabberd_auth_timeout)',
    '#default_value' => variable_get('ejabberd_auth_timeout', '180'),
    '#description' => t("Timeout in seconds"),
  );

  $form['ejabberd_auth_type'] = array(
    '#type' => 'select',
    '#title' => 'Script type (ejabberd_auth_type)',
    '#options' => array(
      0 => 'Simple',
      1 => 'Autonomous',
    ),
    '#default_value' => variable_get('ejabberd_auth_type', 0),
    '#description' => t('ejabberd_auth_type: A simple script linked to Drupal installation (0)
    or an autonomous script (1)?'),
  );
  $form['ejabberd_debug'] = array(
    '#type' => 'textfield',
    '#title' => 'ejabberd debug2',
    '#default_value' => variable_get('ejabberd_debug', '0'),
    '#description' => t("ejabberd_debug settings: 1 = debug messages, 0 = off. many status updates for vars & events"),
  );
  $form['ejabberd_log_to_status'] = array(
    '#type' => 'textfield',
    '#title' => 'ejabberd log to status',
    '#default_value' => variable_get('ejabberd_log_to_status', '0'),
    '#description' => t("ejabberd transaction log to status messages debug: 1 = messages, 0 = off."),
  );
  return system_settings_form($form);
}

/**
 * ejabberd_auth_admin_settings_validate() creates auth script for jabberd connection
 * Uses JabberAuth to create authentication connection setup auth script path to ejabber daemon
 * Writes a file with ejabberd_php_cli, ejabberd_auth_type, ejabberd_auth_timeout,
 * ejabberd_auth_salt 
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function ejabberd_auth_admin_settings_validate($form, &$form_state) {
  $debug = (bool)variable_get('ejabberd_debug', '');
  if ($debug) {drupal_set_message('ejabberd_auth_admin_settings_validate making a auth file');}
  $clean = TRUE;
  if (! is_numeric($form_state['values']['ejabberd_auth_timeout'])) {
    form_set_error('ejabberd_auth_timeout', t("Please, I'd like a number"));
    $clean = FALSE;
  }
  $path = $form_state['values']['ejabberd_auth_path'];
  if (! is_writable(dirname($path))) {
    form_set_error('ejabberd_auth_path', t("Auth script path not writable"));
    $clean = FALSE;
  }
  //auth_path & auth_timeout ok
  // Write the config file
  if ($clean) {
    $f = fopen($path, 'w');
    fwrite($f, "#!" . $form_state['values']['ejabberd_php_cli'] . "\n");
    $inc = dirname(__FILE__) . '/drupalAuth.inc';
    if (1 == $form_state['values']['ejabberd_auth_type']) {
      fwrite($f, file_get_contents($inc));
    }
    else {
      fwrite($f, '<' . "?php\ninclude_once '$inc';\n");
    }
    $timeout = $form_state['values']['ejabberd_auth_timeout'];
    $salt = str_replace("'", "\'", $form_state['values']['ejabberd_auth_salt']);
    $db = (object) parse_url($GLOBALS['db_url']);
    //JabberAuth created by drupalAuth.inc class description
    //write in file about the database, salt & timeout properties
    fwrite($f, <<<EOD
error_reporting(0);

\$auth = new JabberAuth('$GLOBALS[db_url]');
\$auth->salt = '$salt';
\$auth->timeout = $timeout;
\$auth->play(); // We simply start process !

EOD
);
    fclose($f);
    chmod($path, 0755);
    //reports where the ejabberd auth script 
    drupal_set_message('The ejabberd auth script is available at ' . 
      t(filter_xss($form_state['values']['ejabberd_auth_path'])) . ' <br />This may need to be set now in ejabberd.cfg .');
  }
}
